base: core18
name: mpv
version: '0.29.1-nilsboy1'
summary: a free, open source, and cross-platform media player.
description: |
  mpv is a media player based on MPlayer and mplayer2.
  It supports a wide variety of video file formats,
  audio and video codecs, and subtitle types.
  Remember to connect this snap to the removable-media slot,
  otherwise external media won't be accessible!

grade: stable
confinement: strict

apps:
  mpv:
    environment:
      # directory where vapoursynth plugins should reside
      VAPOURSYNTH_PLUGIN_PATH: $SNAP/lib/vapoursynth
    # command: desktop-launch $SNAP/usr/bin/mpv
    command: ./usr/bin/mpv
    plugs:
      - home
      - network
      - opengl
      - optical-drive
      - pulseaudio
      - removable-media
      - unity7
      - x11
      # allow access to ~/.config/mpv
      - config-mpv
      # allow access to system fonts
      - desktop

plugs:
  config-mpv:
    interface: personal-files
    write:
      - $HOME/.config/mpv

parts:
  packages:
    plugin:
      autotools
    source: ./
    override-build: |
      true
    stage-packages:
      - libharfbuzz0b
      - libx265-146
      - libx264-152
      - libssh-4
      - libsnappy1v5
      - libgsm1
      - libfreetype6
      - libfontconfig1
      - samba-libs
      - libpython3.6
      - libsmbclient
      - libgl1
      - libglu1-mesa
      - libglx0
      - libglvnd0
      - libsdl2-2.0-0
      - libxcursor1
      - libxi6
      - libxxf86vm1
      - libslang2
      - libwayland-egl1
      - libegl1
      - liblua5.2-0
      - liblcms2-2
      - libfftw3-3
      - libasound2
      - libass9
      - libatomic1
      - libbluray2
      - libbs2b0
      - libcaca0
      - libcdio-cdda2
      - libcdio-paranoia2
      - libcdio17
      - libchromaprint1
      - libcrystalhd3
      - libdrm2
      - libdvdnav4
      - libdvdread4
      - libegl-mesa0
      - libenca0
      - libfdk-aac1
      - libflite1
      - libfribidi0
      - libgbm1
      - libgme0
      - libguess1
      - libjack0
      - libjpeg62
      - libjpeg8
      - libjpeg9
      - liblzma5
      - libmp3lame0
      - libnetcdf13
      - libomxil-bellagio0
      - libopenal1
      - libopencore-amrnb0
      - libopencore-amrwb0
      - libopus0
      - libpulse0
      - librubberband2
      - libsctp1
      - libshine3
      - libsodium23
      - libsoxr0
      - libspeex1
      - libssh-gcrypt-4
      - libswscale4
      - libtesseract4
      - libtheora0
      - libtwolame0
      - libuchardet0
      - libva-drm2
      - libva-wayland2
      - libva2
      - libvdpau1
      - libvo-amrwbenc0
      - libvpx5
      - libwavpack1
      - libwayland-client0
      - libwayland-cursor0
      - libwebp6
      - libxcb-shape0
      - libxext6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxss1
      - libxv1
      - libxvidcore4
      - libxvmc1
      - libzmq5
      - libzvbi0

  youtube-dl:
    source: https://github.com/rg3/youtube-dl/archive/2017.07.30.1.tar.gz
    plugin: python
    python-version: python3
    after: [ffmpeg]

  mpv:
    source: https://github.com/mpv-player/mpv/archive/v0.29.1.tar.gz
    plugin: waf
    configflags:
      - --enable-cdda
      - --enable-dvdnav
      - --enable-dvdread
      # - --enable-encoding
      - --enable-libmpv-shared
      - --disable-static-build
      # - --enable-libsmbclient
      - --disable-build-date
    override-build: |
      ./bootstrap.py
      snapcraftctl build
    build-packages:  
      - build-essential
      - libharfbuzz-dev
      - libasound2-dev
      - libass-dev
      - libbluray-dev
      - libcdio-paranoia-dev
      - libdvdnav-dev
      - libdvdread-dev
      - libegl1-mesa-dev
      - libenca-dev
      - libfdk-aac-dev
      - libgbm-dev
      - libgl1-mesa-dev
      - libguess-dev
      - libjack-dev
      - libjpeg-dev
      - liblcms2-dev
      - liblua5.2-dev
      - libpulse-dev
      - librubberband-dev
      - libsdl2-dev
      - libssl-dev
      # - libsmbclient-dev
      - libsndio-dev
      - libswscale-dev
      - libuchardet-dev
      - libv4l-dev
      - libva-dev
      - libvdpau-dev
      - libwayland-dev
      - libx11-dev
      - libx264-dev
      - libxinerama-dev
      - libxkbcommon-dev
      - libxrandr-dev
      - libxss-dev
      - libxv-dev
      - pkg-config
      - python
      - python-docutils
      - libpulse0
    after:
      - desktop-glib-only
      - ffmpeg
      - vapoursynth
    organize:
      usr/local: usr/
    # Exclude some junk from the final snap
    prime:
      - -usr/include
      - -usr/share/doc
      - -usr/share/icons
      - -usr/doc
      - -usr/man

  ffmpeg:
    source: https://github.com/FFmpeg/FFmpeg.git
    plugin: autotools
    configflags:
      - --enable-gpl
      - --enable-openssl
      - --enable-nonfree
      - --enable-avresample
      - --enable-avisynth
      - --enable-ladspa
      - --enable-libass
      - --enable-libbluray
      - --enable-libbs2b
      - --enable-libcaca
      - --enable-libcdio
      - --enable-libflite
      - --enable-libfontconfig
      - --enable-libfreetype
      - --enable-libfribidi
      - --enable-libgme
      - --enable-libgsm
      - --enable-libmp3lame
      - --enable-libopenjpeg
      - --enable-libopus
      - --enable-libpulse
      - --enable-librubberband
      - --enable-libshine
      - --enable-libsnappy
      - --enable-libsoxr
      - --enable-libspeex
      - --enable-libssh
      - --enable-libtheora
      - --enable-libtwolame
      - --enable-libvorbis
      - --enable-libvpx
      - --enable-libwavpack
      - --enable-libwebp
      - --enable-libx264
      - --enable-libfdk-aac
      - --enable-libx265
      - --enable-libxvid
      - --enable-libzmq
      - --enable-libzvbi 
      - --enable-omx
      - --enable-openal
      - --enable-opengl
      - --enable-sdl2
      - --enable-shared
      - --disable-static
    build-packages:
      - git
      - g++
      - make
      - autoconf
      - libtool
      - cmake
      - automake
      - build-essential
      - openssl
      - flite1-dev
      - frei0r-plugins-dev
      - ladspa-sdk
      - libass-dev
      - libbluray-dev
      - libbs2b-dev
      - libcaca-dev
      - libcdio-paranoia-dev
      - libchromaprint-dev
      - libcrystalhd-dev
      - libdc1394-22-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libgl1-mesa-dev
      - libgme-dev
      - libgsm1-dev
      - libleptonica-dev
      - liblzma-dev
      - libmp3lame-dev
      - libnetcdf-dev
      - libopenal-dev
      - libomxil-bellagio-dev
      - libopencore-amrnb-dev
      - libopencore-amrwb-dev
      - libopencv-imgproc-dev
      - libopenjp2-7-dev
      - libopus-dev
      - libpulse-dev
      - librubberband-dev
      - libsctp-dev
      - libsdl2-dev
      - libshine-dev
      - libsnappy-dev
      - libsoxr-dev
      - libspeex-dev
      - libssh-gcrypt-dev
      - libtesseract-dev
      - libtheora-dev
      - libtwolame-dev
      - libva-dev
      - libvdpau-dev
      - libvo-amrwbenc-dev
      - libvorbis-dev
      - libvpx-dev
      - libwavpack-dev
      - libwebp-dev
      - libx264-dev
      - libx265-dev
      - libxcb-shape0-dev
      - libxv-dev
      - libxvidcore-dev
      - libxvmc-dev
      - libzmq3-dev
      - libzvbi-dev
      - pkg-config
      - texinfo
      # - nasm
      - zlib1g-dev
    organize:
      usr/local: usr/
    # Exclude some junk from the final snap
    prime:
      - -usr/share/doc
      - -usr/share/icons
      - -usr/include
      - -usr/doc
      - -usr/man

  vapoursynth:
    # NOTE: Releases R36 and R37 seem to have errors
    source: ./dep/vapoursynth-R35.tar.gz
    # replace hardcoded vapoursynth plugin directory with snap one
    override-build: |
      perl -pi -007e 's/\Qstd::string systemPluginDir(tmp ? tmp : VS_PATH_PLUGINDIR);\E/const char *snapPluginDir = getenv("VAPOURSYNTH_PLUGIN_PATH");\nstd::string systemPluginDir(snapPluginDir);\n/gms' src/core/vscore.cpp
      snapcraftctl build
    plugin: autotools
    configflags:
      - --disable-ocr
    build-packages:
      - git
      - g++
      - make
      - autoconf
      - libtool
      - cmake
      - cython
      - automake
      - build-essential
      - yasm
    organize:
      usr/local/lib: usr/lib
    after:
      - zimg

  # # for base: core only:
  # # this release of vapoursynth-mvtools needs newer version than from 16.04
  # nasm:
  #   source: ./dep/nasm-74246c4.tar.gz
  #   plugin: autotools
  #   override-build: |
  #     sh autogen.sh
  #     sh configure
  #     make
  #     # does not work because of missing man files
  #     # make install
  #     /usr/bin/install -c nasm /usr/bin/nasm

  vapoursynth-mvtools:
    source: git://github.com/dubhater/vapoursynth-mvtools.git
    # plugin: autotools
    plugin: meson
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib/vapoursynth/
      cp $SNAPCRAFT_PART_INSTALL/usr/local/lib/x86_64-linux-gnu/* $SNAPCRAFT_PART_INSTALL/lib/vapoursynth/
    build-packages:
      - git
      - g++
      - make
      - autoconf
      - libtool
      - cmake
      - automake
      - build-essential
      - libfftw3-dev
      - nasm
    after:
      # - nasm
      - vapoursynth

  zimg:
    source: ./dep/zimg-release-2.8.tar.gz
    # source: git://github.com/sekrit-twc/zimg.git
    plugin: autotools
    configflags:
      - --enable-x86simd
    build-packages:
      - git
      - g++
      - make
      - autoconf
      - libtool
      - cmake
      - automake
      - build-essential
    organize:
      usr/local: usr/
    # Exclude some junk from the final snap
    prime:
      - -usr/share/doc
      - -usr/share/icons
      - -usr/include
      - -usr/doc
      - -usr/man

  desktop-glib-only:
    build-packages:
    - libglib2.0-dev
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    stage-packages:
    - libglib2.0-bin

