name: Build And Deploy

on:
  push:
    branches:
      - "*"

jobs:
  setup-build-deploy:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set Vars
        run: |-
          echo "REPOSITORY=$(echo ${GITHUB_REPOSITORY#freenet-group/})" >> $GITHUB_ENV
          echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo BUILD_INFO=${SERVICE_NAME}-${GITHUB_SHA}-$(date '+%F-%H%M%S') >> $GITHUB_ENV

          source $GITHUB_ENV
          echo "### Project Configs: "
          cat $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Snap
        run: |-
          docker run -v $(pwd):/app snapcore/snapcraft sh -c "apt update && cd /app && snapcraft"
